apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./templates/serviceaccount.yaml
- ./templates/clusterrole.yaml
- ./templates/clusterrolebinding.yaml
- ./templates/configmap.yaml
- ./templates/daemonset.yaml
